---
version: 1
name: DeepEdit - Prostate
description: MONAI Label App to provide active learning solution using DeepEdit to label prostate on 3D T2-Weighted MRI
dimension: 3
config:
  infer:
    device: cuda
  train:
    name: model_01
    pretrained: true
    device: cuda
    amp: true
    lr: 0.0001
    epochs: 2
    val_split: 0.2
    train_batch_size: 1
    val_batch_size: 1
